# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
settings: # Abstract theme settings
  disqus-id: "xc0d3rz" # Disqus user shortname, will be used to enable comments
  google-site-verification: "XXXXXXXXXXXXXXXXX" # Google site verification, will be useful to verify your blog with google webmaster
author: # Author of the blog, information
  name: "Mohammed Ali" # Author name
  avatar: "/assets/images/author.jpg" # Author avatar
  info: "Alias aperiam at debitis deserunt dignissimos dolorem doloribus, fuga fugiat impedit laudantium magni maxime nihil nisi quidem quisquam sed ullam voluptas voluptatum. Lorem ipsum dolor sit amet, consectetur adipisicing elit." # Author info
  social: # Social links
    facebook: "xC0d3rZ.official"
    twitter: "xc0d3rz"
    nstagram: "xc0d3rz"
    github: "xc0d3rz"
    email:  "x.c0d3rz000@gmail.com"
# jekyll-paginate
paginate: 5 # result no. per page
# jekyll-paginate-category setting
category_dir: "categories" # category dir
category_layout: "category.html" # category layout

gems : # jekyll gems
  - jekyll-paginate
  - jekyll-paginate-category

