# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Mohammed Ali's Blog"
description: > # this means to ignore newlines until "baseurl:"
 Let's rebuild the world togther!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xc0d3rz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
settings: # Abstract theme settings
  disqus-id: "xc0d3rz" # Disqus user shortname, will be used to enable comments
  google-site-verification: "XXXXXXXXXXXXXXXXX" # Google site verification, will be useful to verify your blog with google webmaster
  copyrights: "xcod3rz"
author: # Author of the blog, information
  name: "Mohammed Ali" # Author name
  avatar: "/assets/images/author.jpg" # Author avatar
  info: "I'll never give up, I'll not runaway, i'll be strong, I'll stay, I'll make it one day." # Author info
  social: # Social links
    facebook: "eGMwZDNyeg"
    twitter: "xc0d3rz"
    nstagram: "xc0d3rz"
    github: "xc0d3rz"
    email:  "x.c0d3rz000@gmail.com"
# jekyll-paginate
paginate: 6 # result no. per page
# jekyll-paginate-category setting
category_dir: "categories" # category dir
category_layout: "category.html" # category layout

gems : # jekyll gems
  - jekyll-paginate
  - jekyll-paginate-category

